//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Danhgiathuvien
    {
        public string MaDG { get; set; }
        public int Diem { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayDanhGia { get; set; }
    
        public virtual DocGia DocGia { get; set; }
    }
}
