//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLTVEntities : DbContext
    {
        public QLTVEntities()
            : base("name=QLTVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietNhap> ChiTietNhap { get; set; }
        public virtual DbSet<ChiTietPhieuMuon> ChiTietPhieuMuon { get; set; }
        public virtual DbSet<ChiTietPhieuTra> ChiTietPhieuTra { get; set; }
        public virtual DbSet<ChiTietThanhLy> ChiTietThanhLy { get; set; }
        public virtual DbSet<Danhgiathuvien> Danhgiathuvien { get; set; }
        public virtual DbSet<DocGia> DocGia { get; set; }
        public virtual DbSet<DoiTac> DoiTac { get; set; }
        public virtual DbSet<KeSach> KeSach { get; set; }
        public virtual DbSet<Kho> Kho { get; set; }
        public virtual DbSet<Khu> Khu { get; set; }
        public virtual DbSet<LoaiNV> LoaiNV { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<PhieuMuon> PhieuMuon { get; set; }
        public virtual DbSet<PhieuTra> PhieuTra { get; set; }
        public virtual DbSet<Sach> Sach { get; set; }
        public virtual DbSet<TacGia> TacGia { get; set; }
        public virtual DbSet<TaiKhoanDG> TaiKhoanDG { get; set; }
        public virtual DbSet<TaiKhoanNV> TaiKhoanNV { get; set; }
        public virtual DbSet<TheDocGia> TheDocGia { get; set; }
        public virtual DbSet<TheLoai> TheLoai { get; set; }
        public virtual DbSet<TuaSach> TuaSach { get; set; }
    }
}
