//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.ChiTietPhieuMuon = new HashSet<ChiTietPhieuMuon>();
            this.ChiTietPhieuTra = new HashSet<ChiTietPhieuTra>();
        }
    
        public int MaSach { get; set; }
        public string MaISBN { get; set; }
        public bool TrangThai { get; set; }
    
        public virtual ChiTietNhap ChiTietNhap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuMuon> ChiTietPhieuMuon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuTra> ChiTietPhieuTra { get; set; }
        public virtual ChiTietThanhLy ChiTietThanhLy { get; set; }
        public virtual TuaSach TuaSach { get; set; }
        public virtual KeSach KeSach { get; set; }
        public virtual Kho Kho { get; set; }
    }
}
