//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuaSach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TuaSach()
        {
            this.Sach = new HashSet<Sach>();
        }
    
        public string MaISBN { get; set; }
        public string TenSach { get; set; }
        public string MaTheLoai { get; set; }
        public string MaNXB { get; set; }
        public Nullable<System.DateTime> NgayXuatBan { get; set; }
        public Nullable<int> SoTrang { get; set; }
        public Nullable<int> ChieuDai { get; set; }
        public Nullable<int> ChieuRong { get; set; }
        public string ChatLieuGiay { get; set; }
        public string HinhAnh { get; set; }
        public string MoTa { get; set; }
        public int GiaTien { get; set; }
        public string MaTacGia { get; set; }
    
        public virtual DoiTac DoiTac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sach> Sach { get; set; }
        public virtual TacGia TacGia { get; set; }
        public virtual TheLoai TheLoai { get; set; }
    }
}
